apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: edaf-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: edaf-trigger
      eventSourceName: webhook-eventsource
      eventName: example-webhook
  triggers:
    - template:
        name: trigger-edaf-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: edaf-workflow-
                namespace: argo
              spec:
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: alpine:latest
                      command: ["/bin/sh", "-c"]
                      args: ["echo Triggered EDAF Workflow; sleep 10"]
